create table if not exists public.performance_feedbacks (
  id bigint generated by default as identity primary key,
  page text not null,
  cpu text,
  gpu text,
  ram text,
  storage text,
  game text,
  estimated_fps integer,
  reported_fps integer,
  difference integer,
  feedback_type text not null check (feedback_type in ('close', 'better', 'worse')),
  message text,
  created_at timestamptz not null default now()
);

alter table public.performance_feedbacks enable row level security;

drop policy if exists "Allow anonymous performance feedback inserts"
  on public.performance_feedbacks;

create policy "Allow anonymous performance feedback inserts"
  on public.performance_feedbacks
  for insert
  to anon
  with check (true);

grant insert on public.performance_feedbacks to anon;
